### ISSUE TITLE
Input elements don't allow for btn-arrows

### ISSUE THREAD

**Issue by miggol** [UtrechtUniversity/UU-Bootstrap#20]
The `btn-arrow-left` and `btn-arrow-right` classes seem to work on `<a>` elements, but not with `<input>` (submit) buttons:

![image](https://github.com/UtrechtUniversity/UU-Bootstrap/assets/7064137/fcdb5f1a-0ba3-4ab5-ba80-00811972672c)

The two buttons respectively have `btn-arrow-left` and `btn-arrow-right` set, but only the `<a>` element shows the arrow, while the submit button does not.

**Comment by tymees** [comment]
This is a limitation of using `<input>` elements as buttons, which we cannot fix.

I would suggest you use actual `<button>` elements if you're able:
`<button class="btn btn-primary btn-arrow-right" type="submit">Save & continue</button>`

**Comment by miggol** [comment]
Alright! Thanks for the reply
